language: python
services:
  - docker
script:
  - make build
  - make configure SILENT=1
  - make migrate
  #- make assets # too time-consuming
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
deploy:
  provider: script
  script: make push
  on:
    branch: master
