language: minimal
services:
  - docker
env:
  - ACTIVATE_NOTES=1 ACTIVATE_XQUEUE=1
script:
  - make configure SILENT=1
  - make build
  - make migrate
  #- make assets # too time-consuming
deploy:
  provider: script
  script: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" && make push
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|release\/.*$
