version: "3"

services:
  x-openedx-service:
    &openedx-service
    image: {{ DOCKER_REGISTRY }}{{ DOCKER_IMAGE_OPENEDX_DEV }}
    environment:
      SETTINGS: ${TUTOR_EDX_PLATFORM_SETTINGS:-tutor.development}
    volumes:
      # theme files
      - ../build/openedx/themes:/openedx/themes
      # editable requirements
      - ../build/openedx/requirements:/openedx/requirements

  lms:
    <<: *openedx-service
  cms:
    <<: *openedx-service
  lms_worker:
    <<: *openedx-service
  cms_worker:
    <<: *openedx-service
  
  # Additional service for watching theme changes
  watchthemes:
    <<: *openedx-service
    command: openedx-assets watch-themes --env dev
    restart: unless-stopped
  
  {{ patch("local-docker-compose-dev-services")|indent(2) }}